# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# First, build our storm and zookeeper host groups
- name: Create storm and zookeeper host groups
  hosts: "{{host_inventory}}"
  gather_facts: no
  tasks:
    - include_role:
        name: build-app-host-groups
      vars:
        host_group_list:
          - name: storm
          - name: zookeeper
      when: cloud == 'aws' or cloud == 'osp'
    - include_role:
        name: build-app-host-groups
      vars:
        host_group_list:
          - { name: storm, node_list: "{{host_inventory}}" }
          - { name: zookeeper, inventory: "{{zookeeper_inventory}}", node_list: "{{zookeeper_nodes}}" }
      when: cloud == "vagrant"

# Collect some Zookeeper related facts
- name: Gather facts from Zookeeper host group (if defined)
  hosts: zookeeper
  tasks: []

# and configure our Storm nodes (note that if more than one node is passed in,
# those nodes will be configured as a single Storm cluster)
- name: Install/configure Storm server(s)
  hosts: storm
  gather_facts: no
  vars_files:
    - vars/storm.yml
  vars:
    - combined_package_list: "{{ (default_packages|default([])) | union(storm_package_list) | union((install_packages_by_tag|default({})).storm|default([])) }}"
  # First, determine what the "private" IP addresses of the Zookeeper ensemble are from
  # the meta-data we gathered above in the `hostvars` hash map and the interface name
  # that we'll be configuring Storm to listen on.  Once that's done, ensure that all of the
  # interfaces on the Storm node(s) are up by restarting the network, then gather the facts
  # from our Storm node(s) and deploy Storm to those nodes (configuring them appropriately)
  pre_tasks:
    - set_fact:
        zk_nodes: "{{zookeeper_nodes | map('extract', hostvars, [('ansible_' + storm_iface), 'ipv4', 'address']) | list}}"
    - name: Ensure the network interfaces are up on our Storm node(s)
      service:
        name: network
        state: restarted
      become: true
    - name: Gather facts from the Storm node(s)
      setup:
  roles:
    - role: get-iface-addr
      iface_name: "{{storm_iface}}"
      as_fact: "storm_addr"
    - role: setup-web-proxy
    - role: add-local-repository
      yum_repository: "{{yum_repo_url}}"
      when: yum_repo_url is defined
    - role: install-packages
      package_list: "{{combined_package_list}}"
    - dn-storm
